"""update question model

Revision ID: 8fa0cb875c59
Revises: ebb355241112
Create Date: 2020-10-08 12:01:03.163424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa0cb875c59'
down_revision = 'ebb355241112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
