"""add content to question model

Revision ID: ebb355241112
Revises: 851685bfc78c
Create Date: 2020-10-08 11:59:20.800437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb355241112'
down_revision = '851685bfc78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('content', sa.String(length=2500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'content')
    # ### end Alembic commands ###
