"""fix question model

Revision ID: b1541a667474
Revises: 8fa0cb875c59
Create Date: 2020-10-08 12:01:33.637276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1541a667474'
down_revision = '8fa0cb875c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###
