"""empty message

Revision ID: 5c4923243fe9
Revises: 
Create Date: 2020-10-09 13:13:52.661433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4923243fe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashedPassword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizId', sa.Integer(), nullable=True),
    sa.Column('questionType', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['quizId'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('quizId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quizId'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answerChoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answerJoins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('answerChoiceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answerChoiceId'], ['answerChoices.id'], ),
    sa.ForeignKeyConstraint(['questionId'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incorrectAnswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submissionId', sa.Integer(), nullable=True),
    sa.Column('answerChoiceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answerChoiceId'], ['answerChoices.id'], ),
    sa.ForeignKeyConstraint(['submissionId'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incorrectAnswers')
    op.drop_table('answerJoins')
    op.drop_table('answerChoices')
    op.drop_table('submissions')
    op.drop_table('questions')
    op.drop_table('quizzes')
    op.drop_table('users')
    # ### end Alembic commands ###
